application.title=${spring.application.name} DEV
logging.level.org.atmosphere = debug

# PostgreSQL configuration.
spring.datasource.url=jdbc:postgresql://localhost:5432/kaggle-vis
# These are just credentials for my local postgres instance
spring.datasource.username = postgres
spring.datasource.password = Taq5GnM6i4zmdkgb
# Set to 'validate' for production
spring.jpa.hibernate.ddl-auto = update
# Turn on for debugging
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true

backend.csvLocation=/home/tim/Documents/ETHZ_Notes/Thesis/meta-kaggle
