application.title=${spring.application.name}
logging.level.org.atmosphere=info

# PostgreSQL configuration.
spring.datasource.url=jdbc:postgresql://postgres:5432/kaggle-vis
spring.datasource.username=${POSTGRES_USER}
spring.datasource.password=${POSTGRES_PASSWORD}
spring.jpa.hibernate.ddl-auto=update

# Python server configuration
notebook-processing.base-url=http://server:8081
notebook-processing.notebook-path=process_notebook
notebook-processing.competition-path=process_competition